version: "3"

services:
  bot:
    build: .
    volumes:
      - ".:/workspace"

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
